version: '3'

services:
  taskflybackend:
    image: taskfly.azurecr.io/taskflybackend:latest
    container_name: taskflybackend
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: ""
      MONGO_DATABASE: taskfly
      SPRING_ADMIN_PASSWORD: taskfly
  taskflyfrontend:
    image: taskfly.azurecr.io/taskflyfrontend:dev-5
    container_name: taskflyfrontend
    ports:
      - "80:80"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus:/prometheus
      - /home/azureuser/taskfly/prometheus.yml:/etc/prometheus/prometheus.yml
volumes:
  grafana:
  prometheus:
